"""
Measured reliability of every tip market.

Label rule (applied to an out-of-sample, point-in-time backtest; see core/tip_measure.py):
  skill = 1 - Brier(model) / Brier(base frequency of the market)
  "alta"  : skill > +0.05 AND in the P>=75% band (n >= 50) |predicted - real| <= 5 points
  "bassa" : skill <= 0.01 OR the P>=75% band (n >= 50) is over-estimated by more than 5 points
  "media" : everything else (including markets with too few high-P cases to check calibration)
"bassa" is evaluated first. A probable pick with skill ~ 0 is likely only because the event is
frequent: the model adds no information beyond the base rate, and the software says so.
"""

from typing import Dict, Optional

SKILL_HIGH = 0.05
SKILL_LOW = 0.01
CALIB_TOL = 0.05
BAND_MIN_N = 50
BAND = 0.75


def label_reliability(skill: float, band75: Optional[dict]) -> str:
    """band75 = {"n", "pred", "real"} for P >= 75% (None if empty)."""
    checked = band75 is not None and band75["n"] >= BAND_MIN_N
    gap = (band75["pred"] - band75["real"]) if checked else 0.0
    if skill <= SKILL_LOW or gap > CALIB_TOL:
        return "bassa"
    if skill > SKILL_HIGH and checked and abs(gap) <= CALIB_TOL:
        return "alta"
    return "media"


# MEASURED: key -> {reliability, skill, n, freq}. Generated by research/run_tips_backtest.py.
MEASURED: Dict[str, dict] = {}


def reliability_of(key: str) -> str:
    """Measured label; "media" when the key was never measured."""
    return MEASURED.get(key, {}).get("reliability", "media")
